### ISSUE TITLE
IOS MobileStarter project 

### ISSUE THREAD

**Issue by kyzylisiqi** [iTwin/mobile-samples#302]
Dear Developer(s),
I've encountered an error message while working with the IOS MobileStarter project, and I'm unsure how to resolve it. Could you kindly take a look? Attached are screenshots of the dependency package versions and the error message.
mobile-samples version : mobile-samples-0.22.1
macos version : macOS Sonoma 14.3.1
xcode version : Xcode 15.2
![微信图片_20240222095806](https://github.com/iTwin/mobile-samples/assets/40591687/3f59a1e7-fb25-460f-b305-4511f1e07de6)
![微信图片_20240222095818](https://github.com/iTwin/mobile-samples/assets/40591687/e7dfeb5b-196d-4e57-9c49-872ca8b12a91)

**Comment by tcobbs-bentley** [comment]
Sorry for the lack of a response. The email settings on this repository were not configured correctly. The error you are seeing is not related to iTwin Mobile in any way. Based on a quick investigation, I would say that the problem is that swift-argument-parser is designed for use on macOS. The `Process` class for sure does not exist on iOS, so using a Swift Package that requires it will never work in an iOS app.
